# fly.toml app configuration file generated for d-se on 2026-07-22T21:07:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'd-se'
primary_region = 'ord'

[build]
  dockerfile = 'fly/Dockerfile'

  [build.args]
    VITE_CLERK_PUBLISHABLE_KEY = 'pk_test_c29jaWFsLWZsZWEtMi5jbGVyay5hY2NvdW50cy5kZXYk'
    VITE_COMING_SOON = '1'
    VITE_SITE_URL = 'https://xn--dse-qxa.com'

[env]
  APP_URL = 'https://xn--dse-qxa.com'
  COMING_SOON = '1'
  NODE_ENV = 'production'
  PUBLIC_APP_URL = 'https://xn--dse-qxa.com'
  STOREFRONT_BASE_URL = 'https://xn--dse-qxa.com'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
